### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by mutex36** [green-s/rlhcbfix#1]
I appreciate the effort, but how is changing the thread affinity supposed to affect input lag/responsiveness?
That makes little sense to me.

**Comment by green-s** [comment]
The only reason I entertained the possibility in the first place is because I've noticed that in some games (perhaps ones which don't use the raw input API), changing the process *priority*, which I've had to do in some cases to resolve inconsistent framerates, can have drastic effects on the speed of the mouse. In Battlefield 1 for instance, setting it any higher than normal results in wildly fluctuating speeds, seemingly independent of the framerate, that feel quite similar to the fluctuations in turning speed I've noticed in Rocket League. Priority doesn't seem to have an effect on Rocket League, but since it didn't appear to be a per-frame calculation affecting the mouse in BF1, I'm guessing it's related to the scheduler somehow.
